import type {
  Alert,
  Driver,
  GeoPoint,
  Tenant,
  TrackingMetrics,
  Trip,
  Vehicle,
} from "../types";

const now = Date.now();
const ago = (minutes: number) => new Date(now - minutes * 60000).toISOString();
const later = (minutes: number) =>
  new Date(now + minutes * 60000).toISOString();
const point = (lng: number, lat: number): GeoPoint => ({ lng, lat });
const route = [
  point(-96.797, 32.777),
  point(-96.99, 32.42),
  point(-96.9, 31.98),
  point(-96.61, 31.55),
  point(-96.37, 31.09),
  point(-96.08, 30.62),
  point(-95.72, 30.2),
  point(-95.37, 29.76),
];
const stops = [
  {
    id: "dallas",
    name: "Dallas Warehouse",
    address: "Dallas, TX",
    position: route[0],
    plannedAt: ago(340),
    completedAt: ago(335),
  },
  {
    id: "waco",
    name: "Waco DC",
    address: "Waco, TX",
    position: route[2],
    plannedAt: ago(180),
    completedAt: ago(175),
  },
  {
    id: "college",
    name: "College Station",
    address: "College Station, TX",
    position: route[5],
    plannedAt: ago(40),
    completedAt: ago(36),
  },
  {
    id: "houston",
    name: "Houston Distribution Center",
    address: "1234 Logistics Way, Houston, TX 77032",
    position: route[7],
    plannedAt: later(65),
  },
];
const docs = [
  { id: "bol", name: "Bill of Lading", filename: "BOL-88291.pdf" },
  { id: "pod", name: "Delivery Receipt", filename: "POD-88291.pdf" },
  { id: "temp", name: "Temperature Log", filename: "TempLog-88291.pdf" },
];
const segments = (risk = false, deviation = false) => [
  { id: "done", kind: "completed" as const, points: route.slice(0, 5) },
  ...(risk
    ? [{ id: "risk", kind: "risk" as const, points: route.slice(4, 7) }]
    : []),
  ...(deviation
    ? [
        {
          id: "deviation",
          kind: "deviation" as const,
          points: [route[4], point(-95.93, 30.7), route[6]],
        },
      ]
    : []),
  { id: "planned", kind: "planned" as const, points: route.slice(6) },
];

export const tenants: Tenant[] = [
  { id: "northfreight", name: "NordFreight Logistics" },
  { id: "lonestar", name: "Lone Star Distribution" },
];
export const drivers: Driver[] = [
  { id: "d1", name: "Daniel Agdan", phone: "(214) 555-0187" },
  { id: "d2", name: "Agdan Daniel", phone: "(817) 555-0126" },
  { id: "d3", name: "Danie Agdan", phone: "(512) 555-0148" },
  { id: "d4", name: "Dan Agdan", phone: "(915) 555-0119" },
  { id: "d5", name: "Danyel Agdan", phone: "(956) 555-0194" },
];
export const vehicles: Vehicle[] = [
  {
    id: "v1",
    plateNumber: "VAN-3087",
    type: "53ft Reefer Tractor",
    trailer: "7890",
  },
  { id: "v2", plateNumber: "VAN-2042", type: "Dry Van", trailer: "6401" },
  { id: "v3", plateNumber: "VAN-4567", type: "Box Truck", trailer: "—" },
  {
    id: "v4",
    plateNumber: "VAN-2218",
    type: "53ft Reefer Tractor",
    trailer: "7332",
  },
  { id: "v5", plateNumber: "VAN-3344", type: "Dry Van", trailer: "8211" },
];

const base = {
  tenantId: "northfreight",
  orderId: "ORD-88291",
  route,
  originGeofence: route[0],
  destinationGeofence: route[7],
  destinationWindow: { start: later(40), end: later(160) },
  stops,
  documents: docs,
  distanceTraveledMiles: 178,
  routeAdherencePct: 94,
  totalDurationMinutes: 268,
} as const;
export const trips: Trip[] = [
  {
    ...base,
    id: "TRP-10085",
    status: "delayed",
    statusSince: ago(65),
    vehicleId: "v1",
    driverId: "d1",
    origin: "Dallas, TX",
    destination: "Houston, TX",
    routeSegments: segments(false, false),
    plannedEta: later(0),
    currentEta: later(65),
    progressPct: 72,
    lastGpsAt: ago(2),
    etaVarianceMinutes: 65,
    currentPosition: route[5],
    currentLocation: "I-45 S, Ennis, TX 75119",
    speedKph: 100,
    heading: 182,
    distanceRemainingMiles: 78,
    statusReason: "Traffic congestion on I-45.",
    nextStopId: "houston",
  },
  {
    ...base,
    id: "TRP-10047",
    orderId: "ORD-88274",
    status: "on_track",
    statusSince: ago(140),
    vehicleId: "v2",
    driverId: "d2",
    origin: "Fort Worth, TX",
    destination: "Houston, TX",
    routeSegments: segments(),
    plannedEta: later(95),
    currentEta: later(92),
    progressPct: 64,
    lastGpsAt: ago(1),
    etaVarianceMinutes: -3,
    currentPosition: route[4],
    currentLocation: "I-45 S near Fairfield, TX",
    speedKph: 96,
    heading: 171,
    distanceRemainingMiles: 112,
    statusReason: undefined,
    nextStopId: "college",
  },
  {
    ...base,
    id: "TRP-10052",
    orderId: "ORD-88262",
    status: "at_risk",
    statusSince: ago(25),
    vehicleId: "v3",
    driverId: "d3",
    origin: "Austin, TX",
    destination: "San Antonio, TX",
    routeSegments: segments(true, false),
    plannedEta: later(70),
    currentEta: later(114),
    progressPct: 58,
    lastGpsAt: ago(1),
    etaVarianceMinutes: 44,
    currentPosition: point(-97.76, 30.1),
    currentLocation: "I-35 S near San Marcos, TX",
    speedKph: 72,
    heading: 205,
    distanceRemainingMiles: 52,
    statusReason: "Heavy traffic ahead may affect the delivery window.",
    nextStopId: "houston",
  },
  {
    ...base,
    id: "TRP-10031",
    orderId: "ORD-88231",
    status: "on_track",
    statusSince: ago(215),
    vehicleId: "v4",
    driverId: "d4",
    origin: "Laredo, TX",
    destination: "Corpus Christi, TX",
    routeSegments: segments(),
    plannedEta: later(180),
    currentEta: later(178),
    progressPct: 41,
    lastGpsAt: ago(1),
    etaVarianceMinutes: -2,
    currentPosition: point(-98.91, 27.77),
    currentLocation: "US-59 N near Laredo, TX",
    speedKph: 91,
    heading: 70,
    distanceRemainingMiles: 98,
    statusReason: undefined,
    nextStopId: "college",
  },
  {
    ...base,
    id: "TRP-10091",
    orderId: "ORD-88221",
    status: "offline",
    statusSince: ago(18),
    vehicleId: "v5",
    driverId: "d5",
    origin: "Dallas, TX",
    destination: "Beaumont, TX",
    routeSegments: [
      { id: "done", kind: "completed", points: route.slice(0, 3) },
      { id: "planned", kind: "planned", points: route.slice(2) },
    ],
    plannedEta: later(80),
    currentEta: later(80),
    progressPct: 41,
    lastGpsAt: ago(18),
    etaVarianceMinutes: 0,
    currentPosition: route[2],
    currentLocation: "I-45 S near Corsicana, TX",
    speedKph: null,
    heading: null,
    distanceRemainingMiles: 142,
    statusReason: "GPS communication has been unavailable for 18 min.",
    nextStopId: "college",
  },
  {
    ...base,
    id: "TRP-10012",
    orderId: "ORD-88192",
    status: "completed",
    statusSince: ago(35),
    vehicleId: "v2",
    driverId: "d2",
    origin: "Dallas, TX",
    destination: "Houston, TX",
    routeSegments: [{ id: "done", kind: "completed", points: route }],
    plannedEta: ago(42),
    currentEta: ago(49),
    actualArrival: ago(49),
    progressPct: 100,
    lastGpsAt: ago(49),
    etaVarianceMinutes: -7,
    currentPosition: route[7],
    currentLocation: "Houston Distribution Center",
    speedKph: 0,
    heading: null,
    distanceRemainingMiles: 0,
    distanceTraveledMiles: 248,
    routeAdherencePct: 98,
    totalDurationMinutes: 365,
    statusReason: undefined,
    nextStopId: undefined,
  },
];

export const alerts: Alert[] = [
  {
    id: "a1",
    tripId: "TRP-10085",
    type: "eta_breach",
    severity: "high",
    message: "ETA is 1h 05m past the delivery window",
    location: "I-45 S, Ennis, TX",
    raisedAt: ago(65),
    durationMinutes: 65,
    etaImpactMinutes: 65,
  },
  {
    id: "a2",
    tripId: "TRP-10085",
    type: "traffic_delay",
    severity: "high",
    message: "Heavy traffic on I-45",
    location: "I-45 S, Ennis, TX",
    raisedAt: ago(42),
    durationMinutes: 42,
    etaImpactMinutes: 25,
  },
  {
    id: "a3",
    tripId: "TRP-10052",
    type: "traffic_delay",
    severity: "medium",
    message: "Heavy traffic may affect the delivery window",
    location: "I-35 S, San Marcos, TX",
    raisedAt: ago(25),
    durationMinutes: 25,
    etaImpactMinutes: 44,
  },
  {
    id: "a4",
    tripId: "TRP-10091",
    type: "signal_lost",
    severity: "medium",
    message: "No GPS signal for more than 15 minutes",
    location: "Near Corsicana, TX",
    raisedAt: ago(18),
    durationMinutes: 18,
    etaImpactMinutes: 0,
  },
];

export const metrics: TrackingMetrics = {
  total: 126,
  onTrack: 89,
  atRisk: 21,
  delayed: 12,
  exceptions: 8,
  onTimePerformance: 92.3,
};
