'use client';
import {AlertTriangle,Bell,Box,ChevronDown,ChevronRight,CircleHelp,Clock3,FileText,Filter,Gauge,LayoutDashboard,LocateFixed,Map,MapPin,Maximize2,Menu,MessageSquare,PackageCheck,Search,Send,Settings,SlidersHorizontal,Truck,UserRound,Users,X,ZoomIn,ZoomOut} from 'lucide-react';
import {useMemo,useState} from 'react';
type Status='On Track'|'At Risk'|'Delayed'|'No Signal';
type Trip={id:string;status:Status;route:string;driver:string;eta:string;impact?:string;x:number;y:number};
const trips:Trip[]=[
{id:'TRP-10085',status:'Delayed',route:'Dallas, TX → Houston, TX',driver:'Mike Johnson',eta:'2:15 PM',impact:'+1h 35m',x:68,y:41},
{id:'TRP-10047',status:'On Track',route:'Fort Worth, TX → Phoenix, AZ',driver:'Daniel Martinez',eta:'12:05 PM',x:54,y:64},
{id:'TRP-10052',status:'At Risk',route:'Austin, TX → San Antonio, TX',driver:'Emily Davis',eta:'10:42 AM',impact:'+25m',x:36,y:54},
{id:'TRP-10031',status:'On Track',route:'El Paso, TX → Phoenix, AZ',driver:'Chris Davis',eta:'3:40 PM',x:25,y:27},
{id:'TRP-10053',status:'No Signal',route:'Laredo, TX → Nacogdoches, TX',driver:'Robert Taylor',eta:'—',impact:'18m ago',x:43,y:36}];
const tone:Record<Status,string>={'On Track':'green','At Risk':'amber',Delayed:'red','No Signal':'gray'};
const nav=[[LayoutDashboard,'Control Tower'],[Truck,'Trips'],[Map,'Map View'],[AlertTriangle,'Exceptions'],[Bell,'Alerts'],[LocateFixed,'Geofences'],[MessageSquare,'Messages'],[FileText,'Reports'],[Users,'Drivers'],[Truck,'Vehicles'],[Box,'Documents'],[Gauge,'Analytics'],[Settings,'Settings']] as const;
function StatusPill({status,impact}:{status:Status;impact?:string}){return <span className={`status status-${tone[status]}`}>{status.toUpperCase()}{impact?` · ${impact}`:''}</span>}
function Kpi({label,value,note,badge,color='blue',icon}:{label:string;value:string;note?:string;badge?:string;color?:string;icon?:React.ReactNode}){return <article className="kpi"><div><span>{label}</span><strong>{value}</strong><small className={color==='red'?'danger':''}>{note}</small></div>{badge&&<em className={`badge ${color}`}>{badge}</em>}{icon&&<i className={`kpi-icon ${color}`}>{icon}</i>}</article>}
function Stat({label,value,color}:{label:string;value:string;color?:string}){return <div className="stat"><small>{label}</small><b className={color}>{value}</b></div>}
export default function Home(){
const[selected,setSelected]=useState(trips[0]);const[tab,setTab]=useState<'All'|Status>('All');const[query,setQuery]=useState('');const[filters,setFilters]=useState(false);const[drawer,setDrawer]=useState(true);const[fullscreen,setFullscreen]=useState(false);
const filtered=useMemo(()=>trips.filter(t=>(tab==='All'||t.status===tab)&&`${t.id} ${t.route} ${t.driver}`.toLowerCase().includes(query.toLowerCase())),[tab,query]);
return <main className={`app ${fullscreen?'fullscreen':''}`}><aside className="sidebar"><div className="brand"><MapPin size={29}/><span>TrackMe <b>Suite</b></span></div><nav>{nav.map(([Icon,label],i)=><button key={label} className={i===0?'active':''}><Icon/><span>{label}</span>{label==='Exceptions'&&<em>8</em>}</button>)}</nav><button className="collapse"><ChevronRight/><span>Collapse</span></button></aside>
<section className="shell"><header className="topbar"><button className="mobile-menu"><Menu/></button><div><h1>Control Tower</h1><p>Real-time visibility of in-transit trips and operations</p></div><div className="top-actions"><button className="tenant"><Box/><span><small>Tenant</small>NordFreight Logistics</span><ChevronDown/></button><Search/><Bell/><CircleHelp/><div className="avatar">SJ</div><span className="profile"><b>Sarah Johnson</b><small>Dispatcher</small></span><ChevronDown size={16}/></div></header>
<div className="content"><section className="kpis"><Kpi label="Total In-Transit Trips" value="126" note="Across 8 tenants" icon={<Truck/>}/><Kpi label="On Track" value="89" badge="70.6%" color="green"/><Kpi label="At Risk" value="21" badge="16.7%" color="amber" icon={<AlertTriangle/>}/><Kpi label="Delayed" value="12" badge="9.5%" color="red" icon={<Clock3/>}/><Kpi label="Exceptions" value="8" note="6 requiring attention" color="red"/><Kpi label="Avg. On-Time Performance" value="92.3%" note="This week" color="blue"/></section>
<section className="tower"><aside className="trip-list"><div className="panel-title"><b>Live Trips (126)</b><ChevronDown/></div><div className="tabs">{(['All','On Track','At Risk','Delayed'] as const).map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?'active':''}>{x}<small>{x==='All'?126:x==='On Track'?89:x==='At Risk'?21:12}</small></button>)}</div><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search trips, driver, order, etc."/><SlidersHorizontal/></label><div className="rows">{filtered.map(t=><button key={t.id} className={`trip-row ${selected.id===t.id?'selected':''} edge-${tone[t.status]}`} onClick={()=>{setSelected(t);setDrawer(true)}}><span className={`vehicle ${tone[t.status]}`}><Truck/></span><span><strong>{t.id}</strong><StatusPill status={t.status} impact={t.impact}/><p>{t.route}</p><small>Driver: {t.driver}</small><small>ETA {t.eta}</small></span><ChevronRight/></button>)}</div><button className="view-link">View all trips</button></aside>
<div className="map-stage"><div className="map-toolbar"><span><i/> Live updates</span><button>Auto refresh&nbsp; 30s <ChevronDown/></button><button onClick={()=>setFilters(!filters)}><Filter/> Filters</button><button onClick={()=>setFullscreen(!fullscreen)} aria-label="Toggle fullscreen"><Maximize2/></button></div><div className="map-label label-a">NEW MEXICO</div><div className="map-label label-b">TEXAS</div><div className="map-label label-c">LOUISIANA</div><svg className="routes" viewBox="0 0 1000 570" preserveAspectRatio="none" aria-label="Live logistics routes"><path className="road" d="M0 90 C250 150 320 30 580 100 S820 150 1000 65M40 410 C220 310 360 390 520 260 S780 230 1000 360M180 0 C220 180 160 310 310 570M700 0 C650 180 780 310 730 570"/><path className="route route-red" d="M690 80 C650 160 720 210 680 300 S640 390 680 470"/><path className="route route-green" d="M340 520 C410 450 470 410 540 355"/></svg>{trips.map(t=><button key={t.id} onClick={()=>{setSelected(t);setDrawer(true)}} className={`marker marker-${tone[t.status]} ${selected.id===t.id?'selected':''}`} style={{left:`${t.x}%`,top:`${t.y}%`}} aria-label={`${t.id} ${t.status}`}><Truck/></button>)}<div className="legend"><span><i className="green"/>On Track</span><span><i className="amber"/>At Risk</span><span><i className="red"/>Delayed</span><span><i className="gray"/>No Signal</span></div><div className="zoom"><button><ZoomIn/></button><button><ZoomOut/></button><button><LocateFixed/></button></div>{filters&&<div className="filter-panel"><div><b>Filters</b><button onClick={()=>setFilters(false)}><X/></button></div><label>Tenant<select><option>NordFreight Logistics</option></select></label><label>Status</label>{(['On Track','At Risk','Delayed','No Signal'] as Status[]).map(s=><label className="check" key={s}><input type="checkbox" defaultChecked/>{s}</label>)}<button className="apply" onClick={()=>setFilters(false)}>Apply</button></div>}</div>
{drawer&&<aside className="detail-drawer"><button className="close" onClick={()=>setDrawer(false)}><X/></button><div className="drawer-head"><h2>{selected.id}</h2><StatusPill status={selected.status}/><b>{selected.route}</b><small>Order: ORD-88291</small></div><div className="detail-tabs"><button className="active">Overview</button><button>Timeline</button><button>Stops</button><button>Details</button></div><div className="summary"><Stat label="ETA" value={selected.eta} color={tone[selected.status]}/><Stat label="Distance Remaining" value="78 mi"/><Stat label="Progress" value="72%"/><div className={`progress ${tone[selected.status]}`}><i/></div></div><div className="location"><span className={`dot ${tone[selected.status]}`}/><div><small>Current Location</small><b>I-45 S, Ennis, TX 75119, USA</b><small>Updated 2 min ago</small></div><b>62 mph</b></div><div className="driver-grid"><div><UserRound/><small>Driver</small><b>{selected.driver}</b><a>(214) 555-0187</a></div><div><Truck/><small>Vehicle</small><b>VAN-3087</b><small>Trailer 7890</small></div></div><div className="next-stop"><PackageCheck/><span><small>Next Stop (Delivery)</small><b>Houston Distribution Center</b><small>1234 Logistics Way · Houston, TX 77032</small></span></div><div className="drawer-actions"><button><Send/>Send Message</button><button className="primary">View Trip <ChevronRight/></button></div></aside>}</section>
<section className="exceptions"><div className="panel-title"><b>Active Exceptions (8)</b><a>View all exceptions</a></div><div className="table-wrap"><table><thead><tr><th>Trip ID</th><th>Type</th><th>Severity</th><th>Description</th><th>Location</th><th>Detected At</th><th>Duration</th><th>Driver</th><th>Vehicle</th><th>ETA Impact</th></tr></thead><tbody>{[['TRP-10085','Running Late','High','ETA is 1h 35m past delivery window','I-45 S, Ennis, TX','9:15 AM','1h 35m','Mike Johnson','VAN-3087','+1h 35m'],['TRP-10049','Off Route','High','Deviated 8.2 mi from planned route','US-290, Brenham, TX','8:42 AM','42m','Sarah Williams','VAN-2194','+25m'],['TRP-10052','Stopped Too Long','Medium','Stopped for more than 45 minutes','TX-71, Bastrop, TX','8:10 AM','58m','Emily Davis','VAN-4567','+25m'],['TRP-10053','Lost Signal','Medium','No GPS signal for more than 15 minutes','Near Lufkin, TX','8:05 AM','21m','Robert Taylor','VAN-3344','—']].map((r,i)=><tr key={r[0]} onClick={()=>{const t=trips.find(x=>x.id===r[0]);if(t){setSelected(t);setDrawer(true)}}}><td><i className={i<2?'red':'amber'}/>{r[0]}</td><td>{r[1]}</td><td><span className={`severity ${i<2?'high':'medium'}`}>{r[2]}</span></td>{r.slice(3).map((c,j)=><td className={j===6?'impact':''} key={j}>{c}</td>)}</tr>)}</tbody></table></div></section></div></section></main>}
